import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import {
  ClerkProvider,
} from '@clerk/nextjs';
import { UserProvider } from '@/components/UserProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gray-100 text-gray-900">
        <ClerkProvider>
          <UserProvider>
            <Nav logo="MyRecipes" />
            <main className="w-screen p-5 max-w-full">
              {children}
            </main>
            <Footer />
          </UserProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
