import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useEffect, useState, createContext, useContext } from 'react';
import Nav from '@/components/Nav'
import {
  ClerkProvider,
  useUser,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { UserProvider } from '@/components/UserProvider';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <UserProvider>
          <html lang="en">
            <body>
              <Nav logo="MyRecipes" />
              <main className="w-screen px-5">
                {children}
              </main>        
            </body>
          </html>
        </UserProvider>
    </ClerkProvider>
  );
}
